export const cards = [
  {
    id: 3,
    tagline: "hasan",
    title: "Heading 1",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque aliquet luctus nisi porta consectetur. Vivamus volutpat lectus in ipsum luctus faucibus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec pretium in enim a aliquam. Vivamus ante lacus, sagittis eu elementum eu, pretium id turpis. Nunc nec nibh vehicula, sollicitudin orci vitae, gravida mi. Quisque et lorem sit amet ante interdum sollicitudin. Donec fringilla ac eros eu dignissim. Sed id viverra felis. Donec ultrices magna ac nibh semper commodo ut quis ligula.Curabitur ut nunc consectetur metus porta euismod vitae nec nibh. Donec ultrices ipsum ac eros placerat eleifend. Suspendisse potenti. Proin tempus nulla ultricies felis efficitur, et dapibus justo viverra. Aenean imperdiet ex felis, pharetra iaculis lorem facilisis nec. Nulla posuere neque enim, eu egestas augue congue et. Integer ornare, turpis id posuere interdum, magna ante sodales nibh, nec efficitur est eros vitae elit. Nulla quis urna vitae justo sagittis pharetra. Vestibulum ut nunc ut urna dapibus viverra. Nunc convallis lorem eu ex posuere, a ornare orci vehicula. Ut ullamcorper lacinia mauris. In a congue turpis. Nulla facilisi. Nunc vulputate mi ut mi ultricies, ac tincidunt lectus commodo. Sed vestibulum est eu ante euismod feugiat. Donec at feugiat nisl. Phasellus sit amet porta urna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas imperdiet congue tellus, vel blandit nunc vulputate quis. Cras nibh nulla, suscipit eu viverra ullamcorper, elementum ac nisl. Vivamus in commodo velit. Vivamus dolor ligula, mattis eget lectus nec, tincidunt tempor nibh. Cras pulvinar, diam sit amet bibendum consectetur, metus est molestie mi, vitae finibus neque metus vitae ante. In hac habitasse platea dictumst. Nunc ac dolor sem. Vestibulum id porttitor massa. Praesent vitae ultrices nisl. Fusce ut eros efficitur, dictum odio vel, vulputate turpis. Suspendisse eu dignissim massa. Curabitur sit amet ligula quis libero scelerisque tincidunt. Nam egestas tellus pretium eros ornare congue. Sed sapien dolor, congue eu leo maximus, aliquet laoreet ex. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Morbi vestibulum ac magna in tempor. Pellentesque ut ipsum eu sem auctor fringilla. Cras varius dolor velit, a congue velit semper sed. Phasellus sit amet enim eget odio faucibus scelerisque vel eget tortor. Sed vel mi enim."
  },
  {
    id: 2,
    tagline: "kutay",
    title: "Heading 2",
    description: "Donec pretium in enim a aliquam. Vivamus ante lacus, sagittis eu elementum eu, pretium id turpis. Nunc nec nibh vehicula, sollicitudin orci vitae, gravida mi. Quisque et lorem sit amet ante interdum sollicitudin. Donec fringilla ac eros eu dignissim. Sed id viverra felis. Donec ultrices magna ac nibh semper commodo ut quis ligula.Curabitur ut nunc consectetur metus porta euismod vitae nec nibh. Donec ultrices ipsum ac eros placerat eleifend. Suspendisse potenti. Proin tempus nulla ultricies felis efficitur, et dapibus justo viverra. Aenean imperdiet ex felis, pharetra iaculis lorem facilisis nec. Nulla posuere neque enim, eu egestas augue congue et. Integer ornare, turpis id posuere interdum, magna ante sodales nibh, nec efficitur est eros vitae elit. Nulla quis urna vitae justo sagittis pharetra. Vestibulum ut nunc ut urna dapibus viverra. Nunc convallis lorem eu ex posuere, a ornare orci vehicula. Ut ullamcorper lacinia mauris. In a congue turpis. Nulla facilisi. Nunc vulputate mi ut mi ultricies, ac tincidunt lectus commodo. Sed vestibulum est eu ante euismod feugiat. Donec at feugiat nisl. Phasellus sit amet porta urna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas imperdiet congue tellus, vel blandit nunc vulputate quis."
  },
  {
    id: 1,
    tagline: "teoman",
    title: "Heading 3",
    description: "Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec pretium in enim a aliquam. Vivamus ante lacus, sagittis eu elementum eu, pretium id turpis. Nunc nec nibh vehicula, sollicitudin orci vitae, gravida mi. Quisque et lorem sit amet ante interdum sollicitudin. Donec fringilla ac eros eu dignissim. Sed id viverra felis. Donec ultrices magna ac nibh semper commodo ut quis ligula.Curabitur ut nunc consectetur metus porta euismod vitae nec nibh. Donec ultrices ipsum ac eros placerat eleifend. Suspendisse potenti. Proin tempus nulla ultricies felis efficitur, et dapibus justo viverra."
  },
]